### ISSUE TITLE
Cannot drag shimejis

### ISSUE THREAD

**Issue by nojvspine** [CluelessCatBurger/wl_shimeji#19]
When I'm clicking and holding on the shimeji it starts dragging animation, but as soon as i drag mouse even a little bit it gets released.

Distro: Arch Linux
WM: Hyprland

**Comment by CluelessCatBurger** [comment]
After some testing, I found out that when the input region is disabled while a button is pressed and the user moves the cursor, Hyprland sends a release button event for the wl_pointer, followed by wl_pointer.leave() and then wl_pointer.enter(). I'm not sure if that behavior is intended. If I'm not mistaken, the specification doesn't mention anything about such scenarios, so it might be compositor-dependent. I will ask the Hyprland team if this is intended behavior, and if so, I will need to rewrite the input handling in wl_shimeji. Currently, I'm busy, so it may be delayed by 1-2 months.

**Comment by Honkazel** [comment]
https://github.com/user-attachments/assets/8e392f49-cc59-46cf-abcf-e90ded5b8395
Is that an intended behavior?
Affected compositors: Sway, River, Cosmic

**Comment by CluelessCatBurger** [comment]
> https://github.com/user-attachments/assets/8e392f49-cc59-46cf-abcf-e90ded5b8395 Is that an intended behavior? Affected compositors: Sway, River, Cosmic

What exactly is happening here? Can you explain steps to reproduce and send logs with WAYLAND_DEBUG=1 when this happens?

**Comment by Honkazel** [comment]
[shimeji-sway.log](https://github.com/user-attachments/files/18555641/shimeji-sway.log)
How2repro:
1) Launch sway
2) Launch shimeji
3) Drag the shimeji and move the cursor
4) ???
5) Shimeji flies to the stratosphere even when i didn't release mouse or shimeji's(subsurface one) hanging(😢) and don't move after the cursor

Maybe it's intended behaviour?

**Comment by CluelessCatBurger** [comment]
@Honkazel Should be fixed now, can you reproduce this on sway/river/cosmic after c5acbdc?

**Comment by nojvspine** [comment]
Can confirm that after c5acbdc dragging works on Hyprland.

**Comment by Honkazel** [comment]
https://github.com/user-attachments/assets/2eaf102a-6b56-4e9f-9f49-716f7d8a3727

[shimeji-sway.log](https://github.com/user-attachments/files/18598714/shimeji-sway.log)

Half fixed

**Comment by CluelessCatBurger** [comment]
Are you sure you are using the latest commit? (392a83d5658f283ace77b0c839d5a201cebc8784)

**Comment by Honkazel** [comment]
Fixed, thanks @CluelessCatBurger

**Comment by nojvspine** [comment]
After updating Hyprland to new version (0.48.0) dragging is again broken

[shimeji.log](https://github.com/user-attachments/files/19460794/shimeji.log)

**Comment by nojvspine** [comment]
well now that i tried it again, it now works. don't know what exactly changed. if anything changes again i'll post about it

**Comment by Readf0x** [comment]
I'm running version v0.49.0 ([`9958d29`](https://github.com/hyprwm/hyprland/commit/9958d297641b5c84dcff93f9039d80a5ad37ab00)) and it's still a problem for me.

**Comment by CluelessCatBurger** [comment]
@Readf0x you can't drag shimejis or dragging is broken? If you can't drag them, dragging may be disabled via config, and you should make sure that `shimejictl config list` says that dragging is enabled

**Comment by CluelessCatBurger** [comment]
@Readf0x what if you unset XDG_CURRENT_DESKTOP and then run `shimeji-overlayd -se`?

**Comment by Readf0x** [comment]
@CluelessCatBurger 
Functionality is improved! Mascots can actually be dragged, however I have to click a second time to cease dragging.

**Comment by CluelessCatBurger** [comment]
Hmmm, so looks like my workaround is broken now
@nojvspine can you please check if dragging works for you with unset XDG_CURRENT_DESKTOP and if it even set to Hyprland in your case, if you still using hyprland ofc?

**Comment by nojvspine** [comment]
I'm using uwsm so it is set to Hyprland, but dragging works even without it. Just so that grabbing works like a toggle instead of hold, you need to click second time to release shimejis.

**Comment by Readf0x** [comment]
> I'm using uwsm so it is set to Hyprland, but dragging works even without it. Just so that grabbing works like a toggle instead of hold, you need to click second time to release shimejis.

That's the behavior I get when XDG_CURRENT_DESKTOP is unset, so it sounds like the code isn't even functioning for you.

**Comment by nojvspine** [comment]
@Readf0x yes, I meant to say that if I run daemon with this variable unset I get this behavior, and if it is set then everything works normal
